CREATE TABLE user_table (
	id 		INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	login 	VARCHAR(128),
    password 	VARCHAR(254),
	email 	VARCHAR(254),
	name 	VARCHAR(128),
	surname VARCHAR(128),
	patronymic VARCHAR(128)
);

INSERT INTO user_table (id, login, password, email, name, surname, patronymic) VALUES
  (1, 'kant', 'kritika', 'kant@mail.ru', 'Иммануил', 'Кант', ''),
  (2, 'gegel', 'dialektica', 'gegel@mail.ru', 'Вильгельм', 'Гегель', 'Фридрих')
